services:
  - type: web
    name: yunono-youtube
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
    regions:
      - oregon
